### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Mellorison**
#Issue 32 Updates
- Added a new form 'photos' to create Image View Widget in.
- Updated the gradle and added volley tools in case of server based image storage access needs.
- Added an EXTERNAL_MEDIA_STORAGE Access to the cervical cancer Android Manifest.
- Added Java class 'CameraUtils' in case of Camera use/access within application.
- Added SmartCerv Cervical Cancer logos to res drawable directory.

### CODE REVIEW

**Comment by kaykabwe** [comment]
Just rebased my code on this branch sucessfully and pushed by that volley thing wont allow my project to build now.

**Comment by csamiselo** [comment]
merged locally and able to view all additions and changes to develop branch with @kaykabwe

**Comment by kaykabwe** [comment]
Successfully merged issue#15 unfinished code. Am able to see the other members changes on the app

**Comment by kaykabwe** [comment]
Successfully merged issue#15 unfinished code. Am able to see the other members changes on the app

**Pull request closed without merging**
