### PR TITLE
Issue#32

### PR DESCRIPTION
**Pull request by Mellorison**

### CODE REVIEW

**Comment by Mellorison** [comment]
Created CameraButton Widget and added it to the Test Results Json Form.
Application is able to Access Camera and Take Photos, But Not able to save photos in application yet.

**Comment by hallix** [comment]
@Mellorison Please resolve the conflicts and request for a review.

**Comment by hallix** [comment]
@Mellorison Please resolve the conflicts and request for a review.

**Comment by Mellorison** [comment]
Added Partial Evaluation section of LEEP form.

**Comment by hallix** [comment]
@Mellorison fix crash on VIA -> Test Result form for **Image load** and **Take Photo** widgets when user presses back to cancel the intent.

**Pull request merged**
